#!/bin/bash
#Script para informações sobre a hierarquia de memória do computador.
#Prof. Filippo Valiante Filho
#Version 1.01
#2018-05-15


#Verificação prévia da configuração de swap
#O cálculo do % da memória principal a partir da qual se inicia o uso do swap é feito com $((100-valorswap))
valorswap=$(cat /proc/sys/vm/swappiness)


#Início das informações
clear

#MEMÓRIA CACHE
echo -e "\nMEMÓRIA CACHE:\n"
echo -e -n "Microprocessador ["$(lscpu | grep -i nome || lscpu | grep -i name)"] com a seguinte configuração de memória cache:\n\n"
lscpu | grep cache


#MEMÓRIA PRINCIPAL
echo -e "\n\nMEMÓRIA PRINCIPAL:\n"
free -h | head -n2


#MEMÓRIA SECUNDÁRIA
echo -e "\n\nMEMÓRIA SECUNDÁRIA:\n"
lsblk --output VENDOR,MODEL,STATE,TRAN,NAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,HOTPLUG --exclude 7
#df -ha | head -n1 && df -ha | grep -i mnt || df -ha | grep -i sd


#MEMÓRIA VIRTUAL
echo -e "\n\nMEMÓRIA VIRTUAL - SWAP:\n"
free -h | head -n1
free -h | grep -i swap
echo -e -n "\nSwap configurado em ["$(cut -c 1-14 < /proc/swaps | tail -n1)"].\n"


echo -e "\n\nMEMÓRIA VIRTUAL - TOTAL:\n"
free -h | head -n1
free -ht | tail -n1

echo -e "\n\nO espaço de endereçamento está organizado da seguinte forma:\n"
cat /proc/cpuinfo | grep address | head -n1

echo -e "\n\nSeu sistema está configurado para começar a usar swap a partir de [$((100-valorswap))%] de uso da memória principal.\n"

echo -e 'Para alterar edite como superusuário o arquivo /etc/sysctl.conf e acrescente, ou remova o comentário, da linha vm.swappiness. Por exemplo, vm.swappiness=10 indica que o swap inicia apenas com 90% de uso da memória principal. O valor padrão 60 indica que o swap inicia a partir de 40% de uso da memória principal.\n'

echo ""
